#!/bin/bash

NOISE=0
if tty -s
then
	NOISE=1
fi

# The base station for the Ambient Weather WS-1400-IP weather station
#  sometimes gets derpy and has a high ping RTT. This script monitors that
#  in a nagios-compatible fashion.
host=weather.lh.db94.net

rtt=$(ping -c 4 $host 2> /dev/null | grep rtt | cut -f5 -d/)

# Drop any decimals
rtt=${rtt%.*}

message() {
	ES=$1
	shift
	(( NOISE )) && echo "$*" && echo "Exit status: $ES"
	echo "$*" | mail -s "Lakehouse weather ping" db94wookie@gmail.com
	exit $ES
}

if [[ -z $rtt ]]
then
	message 2 "CRITICAL: No response to ping."
fi

if (( rtt > 200 ))
then
	# Shit's gotten derpy... Reboot it.
	curl -s http://${host}/msgreboot.htm > /dev/null
	#message 2 "CRITICAL: $rtt is over 200ms threshold. Rebooting."
fi

#if (( rtt > 100 ))
#then
#	message 1 "WARNING: Over 100ms response."
#fi

(( NOISE )) && echo "OK: RTT is $rtt"
exit 0
