#!/bin/bash

#
# internet-monitor
#
# Purpose:  Monitor the internet connection, making sure we can see it.
#           If not, reboot the router.
#

# My own name
COMMAND="${0##*/}"

# Debugging
exec 2> ~/tmp/debug-$COMMAND.$$
set -x

# COMMANDS
ip=/bin/ip
awk=/usr/sbin/awk
ssh=/usr/bin/ssh
fping=/usr/bin/fping
wall=/usr/bin/wall
logger=/usr/bin/logger

# Define a function to log an error message to different locations
# If we can't alert externally, then we'll make as much noise as we can locally.
# Log the message to STDOUT, STDERR, wall, and syslog.
function alert {
    # Echo to STDOUT and all logged-in users
    echo "$*" | tee >( $wall )
    # Echo to STDERR
    echo "$*" >&2
    # Echo to syslog
    $logger -p user.crit -t $COMMAND "$*"
}
    
# error out if fping isn't found
if [[ ! -x $fping ]]
then
    alert "ERROR: I need fping. Please install it."
    exit 1
fi

# Get alert addresses from the monitor script's config
monconfig=~/.monitor.cfg
if [[ -r $monconfig ]]
then
    . $monconfig
fi

# Make some noise if the alert address isn't set
if [[ -z "$alert" ]]
then
    alert "WARNING: Can't email alerts if \"alert\" isn't set in $monconfig"
fi

# Find my router from the default route
#router=$($ip route show | $awk '/default/ {print $3}')
# ... or, hardcode it:
router='192.168.113.1'

# Username for ssh connection to router
routeruser='root'

# Private key to log into the router's ssh interface
key=~/.ssh/router-control

# Use google's public DNS as an external address
external='8.8.8.8'


# Ping the router - if we can't see it, no point going on.
if ! $fping -q $router
then
    alert "ERROR: Can't ping the router, can't continue."
    exit 1
fi

# Ping the external address
for try in {1..3}
do
    if $fping -q $external
    then
        # We can ping outbound, the internets are fine, exit clean.
        : Successfully pinged $external
        exit 0
    fi
    # Wait a minute to try again
    sleep 60
done

# If we get to this point, we couldn't ping external in three tries at minute intervals.
# Reboot the router
: Rebooting the router
$ssh -i $key $routeruser@$router reboot

# Wait a minute
sleep 60

# Wait until the router pings, sixteen tries at 15 second intervals (four minutes)
for try in {1..16}
do
    : Trying to ping the router
    if $fping -q $router
    then
        # Check again if we can get outbound.
        #  If we can, send an email to the $alert addresses
        if $fping -q $external
        then
            # Success! Send an email to the alert address
            : Success, sending alert email
            echo "Couldn't ping $external so I rebooted the router." | mail -s "Lake internet alert" $alert
            exit 0
        else
            # Couldn't ping out, something's fucked up, nothing else we can do.
            : Failed to re-establish communication outside.
            alert "ERROR: couldn't get external after rebooting router!"
            exit 1
        fi
    fi
    sleep 15
done

# If we get here, we couldn't reconnect to the router after waiting for it to come back.
# Nothing else to do but make all the noise we can here.
: Failed to re-establish contact with the router.
alert "ERROR: Rebooted router $router, it doesn't seem to have come back."
exit 1
