#!/bin/bash

# Debugging set if var "_DEBUG" is non-null
_DEBUG=1
if [[ -n $_DEBUG ]]
then
	PS4='$LINENO:	'
	exec 2> ~/tmp/debug-${0##*/}
	set -x
fi

##### Shell options
# Enable extended globs
shopt -s extglob

##### VAR DEFS #####
# Use this file for var defs which override these defaults
inifile="$HOME/.monitor.cfg"
# Script to send messages to slack
slack=~/bin/slack
# Base dir
dir='/home/cmh/www'
# File to indicate that a warning has been issued
warnfile=$dir/warning
# File to make alerts STFU
stfufile=$dir/stfu
# Number of minutes to expire the warning file
warnexpire=240
# Set date vars
eval $(/bin/date +"yr=%y mo=%m da=%d h24=%H h12=%I mi=%M pm=%p es=%s")
# Drop the leading zero on the 12h hour value
h12=${h12#0}
# Round the epoch seconds to the latest minute
es=$((es-(es%60)))
# Storage directory
stodir="$dir/storage/$yr/$mo/$da"
# RRD dir
rrddir="$dir/../rrd"
# Output file for the webcam
file="$stodir/$yr$mo$da-$h24$mi.jpg"
# Filename for the most recent file
now="$dir/now.jpg"
# Default times to start and stop taking photos - overriden by suntimes below
photostart=0600
photostop=1800
# Read the times from an external file if it exists
suntimes=~/.suntimes
if [[ -r $suntimes ]]
then
	. $suntimes
fi
# Swap out this image if the taken photo is too dark
dark="$dir/images/toodark.jpg"
# Swap out this image if we're outside of the camera's time range
nophoto="$dir/images/nophoto.jpg"
# Swap out this image if no camera is detected
nocamera="$dir/images/nocamera.jpg"
# Output to this HTML page
out="$dir/now.html"
# Track temps in this csv (rotate daily)
csv="$stodir/temp-$yr$mo$da.csv"
# Track CPU temps in this CSV
cpucsv="$stodir/cputemp-$yr$mo$da.csv"
# Low temperature - alert if inside temp is under this (deg F)
lowtemp=48
warntemp=52
# Table background colors: green = okay
inBkg='#CCFFCC'
outBkg='#CCFFCC'
timeBkg='#CCCCFF'
# Default to non-verbose output
NOISE=0

# Grab some vars from the ini file
#  * overrides defaults from above
if [[ -r $inifile ]]
then
	. $inifile
else
	echo "WARNING: ini file $inifile unreadable" >&2
fi

# If the "alert" address isn't set after reading the inifile,
#  we can't send emails to anyone so will throw messages to whatever
#  we can locally and hope they get seen.
if [[ -z $alert ]]
then
	# alert address not set! Log some errors and hope they're seen
	msg="$0 WARNING: No alert address set! Please set the variable \"alert\" in $inifile with a valid email address."
	# Send to syslog
	logger -t MONITOR -p user.crit "$msg"
	# Send to slack
	$slack -c 'Lake house' -i house 'WARNING: No alert adress set for lakehouse monitor'
	# Send to all logged-in users and STDOUT
	echo "$msg" | tee >( /usr/bin/wall )
	# Send to STDERR
	echo "$msg" >&2
fi

# Set the URL of the Ambient Weather weather station if the IP is set
if [[ -n $weather ]]
then
	# URL of the live data page on the weather station
	url="http://${weather}/livedata.htm"
fi

# If i've set "wustation" in my .monitor.cfg, set the URL of the WeatherUnderground page for this weather station
if [[ -n $wustation ]]
then
	wunderurl="http://www.wunderground.com/personal-weather-station/dashboard?ID=$wustation"
fi

##### FUNCTIONS DEFS #####
function noise {
	(( NOISE )) && echo "$*"
}

# Get my temperature from the DS18B20 1-wire sensor
function mytemp-ds {
	# Read the current temp from the DS18B20 if it is attached
	# Note: This code won't handle more than one sensor.
	w1=$(ls /sys/bus/w1/devices/*/w1_slave)
	if [[ -r $w1 ]]
	then
		# Read the temp
		myTemp=$(awk -F= '/t=/ {print $2}' $w1)
		# Convert to millideg F
		myTemp=$((myTemp * 9/5 + 32000))
		# Convert to deg F
		myTemp=${myTemp:0:-3}.${myTemp:0-3}
	fi
}

# Get my temperature from the DHT sensor
function mytemp-dht {
	# Read the current temp from the DHT22 sensor on pin 17
	eval $(~/bin/dht 17)
}

# Check if we're running from an interactive session
if /usr/bin/tty -s
then
	# Can be overridden with "-q" option below
	NOISE=1
fi

# Options processing
while getopts ":qv" opt
do
	case $opt in
		q)	# Run quietly
			NOISE=0;;
		v)	# Run verbosely
			NOISE=1;;
		*)	# Any other option triggers usage
			echo "Usage: $0 [ -q | -v ]"
			echo "	-q	Run quietly"
			echo "	-v	Run verbosely"
			echo
			exit 1
			;;
	esac
done
shift $((OPTIND-1))

# Start off in the web dir
noise "Running in $dir"
cd $dir

# Make the storage dir (-p exits quietly if the dir exists)
mkdir -p $stodir

# Check to see if the onboard camera is connected
#  The "vcgencmd get_camera" returns "supported=# detected=#" where # is 0/1
#  Set these vars using eval so we can just check and see if the camera is detected
#  and skip all the other work
eval $( vcgencmd get_camera )
if (( detected ))
then
	# Take a photo with the onboard camera if the time is between 6am and 6pm
	#  NB: have to specify values as base 10 with "10#" prefix to avoid 08/09 being
	#	  interpreted as bad octal values. Bash will interpret a number with a leading
	#	  zero as octal.
	if (( 10#$h24$mi > 10#$photostart && 10#$h24$mi < 10#$photostop ))
	then
		noise "Taking photo with webcam"
		noise "	   file:	$file"
		noise "	current:	$now"
		/usr/bin/raspistill -n -w 640 -h 480 -vf -hf -e jpg -awb fluorescent -x none -ev +1 -sa 0 -o $file -l $now

		# Check to see if the image is too dark
		noise "Checking photo exposure"
		mean="$(identify -format '%[mean]' $now)"
		# Drop the decimal (bash doesn't understand fp numbers)
		mean="${mean%%.*}"

		# 1000 seems to be a good level to qualify as "too dark".
		if (( mean < 1000 ))
		then
			noise "Replacing photo with \"too dark\" message"
			rm $now
			ln -s $dark $now
		fi
	else
		# Outside the camera's runtime (aka night) - swap in the no photo image
		noise "Skipping photo due to time"
		if [[ ! $now -ef $nophoto ]]
		then
			rm $now
			ln -s $nophoto $now
		fi
	fi
else
	# Stuff to do when the camera isn't there.
	if [[ ! $now -ef $nocamera ]]
	then
		rm $now
		ln -s $nocamera $now
	fi
fi

# Get the temp from the attached sensor
mytemp-ds

# Get the temps from the weather station
#  * Grab the live data page
#  * grep the lines for inside and outside temp and humidity
#  * output them in the form "inTemp=64.2"
#  * eval those lines to set the values in those variables
noise "Getting temp/humidity info from weather station"
for try in {1..3}
do
	# Get times before and after trying to connect to the weather station
	before=$(/bin/date +%s)
	eval $(curl -s $url | egrep "(in|out)(Temp|Humi|BattSta)" | sed 's/^.*name="//; s/".*value=/=/; s/" .*$/"/')
	exitstat=$?
	after=$(/bin/date +%s)

	# Exit the loop if we have a valid reading for inTemp
	if [[ $inTemp == +([0-9]).[0-9] ]]
	then
		break
	fi
done

# Use my temp over the weather station if it's set
refTemp=${myTemp:-$inTemp}

# Trim decimal places if refTemp has too many
#  Todo: figure out how to nicely trim arbitrary number of decimal places to one
if [[ $refTemp == *.??? ]]
then
	refTemp=${refTemp%??}
fi

# Alert to everyone if it drops below the "lowtemp" setting
if (( ${refTemp%%.*} < lowtemp ))
then
	# Set table background to red to indicate alert
	inBkg='#ffcccc'
	# Send an alert on the low temp condition
	noise "Alerting on low temp condition ($inTemp)"
	if [[ ! -f $stfufile ]]
	then
		echo -e "ALERT: Inside temp is $refTemp!\nLast warning:\n$(< $warnfile)" | mail -s "ALERT: Lakehouse temp" $alert
		$slack -u 'Lake house' -i 'cold-face' "ALERT: Inside temp is $refTemp!\nLast warning:\n$(< $warnfile)"
	fi
# Alert to the first mail address if it's below "warntemp"
#  use a warning file to not warn incessantly
elif (( ${refTemp%.*} < warntemp ))
then
	# Set table background to orange to indicate warning
	inBkg='#ffcc99'
	# If there's no warnfile, create it and send a warning
	if [[ ! -f $warnfile ]]
	then
		# Send a warning on the low temp condition to the first email in "alert"
		noise "Warning on low temp condition ($inTemp)"
		# Create the warning file
		echo "$yr$mo$da-$h24$mi warning temp: $refTemp under $warntemp - critical $lowtemp" > $warnfile
		# Set a warning message (sent below)
		msg="WARNING: Inside temp is $refTemp!\n$(< $warnfile)"
	elif [[ -n $(/usr/bin/find $warnfile -mmin +$warnexpire) ]]
	then
		# Update the time on the warning file
		touch $warnfile
		# Set a warning message (sent below)
		msg="WARNING: Inside temp is $refTemp!\n$(< $warnfile)"
	fi

	# If a warning message has been set, send it.
	if [[ -n $msg ]]
	then
		echo -e "$msg" | mail -s "Lakehouse temp warning" ${alert%%,*}
		$slack -u 'Lake house' -i 'wrong' ":snowflake: *WARNING:* Lake house temp warning\n$msg"
	fi
# Clean up if we're in an ok condition
else
	# Temperature is okay
	# Remove the STFU file
	/bin/rm -f $stfufile
	# If the warnfile exists, clear it and send a recovery email
	if [[ -f $warnfile ]]
	then
		echo -e "RECOVERED: Temperature is now $refTemp, above $warntemp\nLast warning: $(< $warnfile)" | mail -s "Lakehouse temp warning" ${alert%%,*}
		rm $warnfile
	fi
fi

# Tag the background if it's under freezing outside
if (( ${outTemp%.*} < 32 ))
then
	# This is orange
	outBkg='#ffcc99'
fi

# Log the values to the csv file
noise "Updating data points to CSV file $csv"
echo "$es,$inTemp,$inHumi,$outTemp,$outHumi${myTemp:+,$myTemp}${myHumi:+,$myHumi}" >> $csv

# Get the CPU temp
cpuTempC=$(< /sys/class/thermal/thermal_zone0/temp)
# convert to fahrenheit (preserving the x1000 scale to fake FP math)
cpuTemp=$((cpuTempC*9/5+32000))
# convert to decimal
cpuTemp="${cpuTemp:0:-3}.${cpuTemp:0-3}"
# Log it to CSV
echo "$es,$cpuTemp" >> $cpucsv
#logger -t cpuTemp -p user.info "got cpu temp $cpuTemp at timestamp $es"
# Check it and alert if it's ridiculously high
if (( cpuTempC > 80000 ))
then
	echo "CPU temp high - $cpuTemp" | mail -s "LakePi CPU temp alert" $alert
fi

# Update the RRD files and graphs
for rrd in inTemp outTemp cpuTemp myTemp myHumi
do
	# Get the value
	value=$(eval echo \$$rrd)

	# Don't update if the value is null.
	if [[ -z $value ]]
	then
		noise "Null value for $rrd - skipping the update"
		continue
	fi

	# Update the RRD file
	noise "Updating the RRD graph $rrd with value $value"
	if /usr/bin/rrdtool updatev $rrddir/${rrd}.rrd $es:$value >&2
	then
		: RRD Updated $rrd with value $value okay - $es
	else
		: RRD FAILED TO UPDATE - $es
	fi
done

# One graph to graph them all
#  * Inside temp from weatherstation in dark blue
#  * Outside temp from weatherstation in black
#  * Inside temp from Pi sensor in blue
#  * Horizontal line at freezing in cyan
#  * Dashed horizontal line at the low temp warning point in orange
#  * Dashed horizontal line at the low temp critical point in red
/usr/bin/rrdtool graph $dir/tempGraph.png -w 640 -h 320 -D \
	"DEF:myTemp=$rrddir/myTemp.rrd:myTemp:AVERAGE" "LINE4:myTemp#0000FF:Inside" \
	"DEF:inTemp=$rrddir/inTemp.rrd:inTemp:AVERAGE" "LINE2:inTemp#9999FF:Mantel" \
	"DEF:outTemp=$rrddir/outTemp.rrd:outTemp:AVERAGE" "LINE4:outTemp#000000:Outside" \
	"DEF:heat=$rrddir/heat.rrd:heat:MAX" "TICK:heat#FF333366:1:Heat" \
	"HRULE:$warntemp#FF9900:Warning:dashes" \
	"HRULE:$lowtemp#FF0000:Alert:dashes" \
	"HRULE:32#00FFFF:Freezing" > /dev/null

# Check battery status on the weather station
if [[ $inBattSta != 'Normal' || $outBattSta1 != 'Normal' ]]
then
	battwarn="<TR VALIGN=CENTER><TD ALIGN=RIGHT COLSPAN=3 BGCOLOR=#ffcccc>Warning! Inside battery status: $inBattSta Outside battery status: ${outBattSta1}</TD></TR>"
fi

# Write the HTML status file
noise "Updating HTML file"
cat << EOF > $out
<HEAD>
<meta http-equiv="refresh" content="300">
<TITLE>Lakehouse monitor</TITLE>
</HEAD>
<BODY>
<TABLE CELLPADDING=3>
  <!-- NO PHOTO FROM THIS PI <TR VALIGN=CENTER><TD ALIGN=CENTER COLSPAN=3><IMG SRC=now.jpg></TD></TR> -->
  <TR VALIGN=CENTER><TD ALIGN=CENTER COLSPAN=3><IMG SRC=lake.jpg></TD></TR>
  <TR VALIGN=CENTER><TD ALIGN=RIGHT><FONT SIZE=+10>Inside temp</TD><TH BGCOLOR=$inBkg><FONT SIZE=+10>$refTemp</TH><TD WIDTH=100><FONT SIZE=+7>F</TD></TR>
  <TR VALIGN=CENTER><TD ALIGN=RIGHT><FONT SIZE=+10>Outside temp</TD><TH BGCOLOR=$outBkg><FONT SIZE=+10>$outTemp</TH><TD><FONT SIZE=+7>F</TD></TR>
  <TR VALIGN=CENTER><TD ALIGN=CENTER COLSPAN=3>Temperature trends over the past 24 hours:<BR><A HREF=$wunderurl TARGET="_blank"><IMG SRC=tempGraph.png></A><BR>
  <TR VALIGN=CENTER><TD ALIGN=RIGHT COLSPAN=3>Oil tank: $(~/bin/get-tanklevel) - Last run $h12:$mi $pm</TD></TR>
  $battwarn
</TD></TR></TABLE>
</BODY>
EOF

# Holding area for lines we don't want to run at the moment:
#  <TR VALIGN=CENTER><TD ALIGN=RIGHT COLSPAN=3>Photo last updated: $(/bin/date -d @$(stat -c %Y $now) +"%m/%d/%y %l:%M %P")</TD></TR>

##### END #####
noise "	...completed successfully!"
exit 0
