#!/bin/bash

# See: https://elinux.org/RPi_HardwareHistory

# Get the CPU revision 
revision=$(awk '/Revision/ {print $3}' /proc/cpuinfo)

# "1000" prefix means over-volted, remove it.
revision=${revision#1000}

case $revision in
	0002|0003|0004|0005|0006)
		echo "Model B 256MB";;
	0007|0008|0009)
		echo "Model A 256MB";;
	000d|000e|000f)
		echo "Model B 512MB";;
	0010|0013)
		echo "Model B+ 512MB";;
	0011|0014)
		echo "Compute Module 1 512MB";;
	0012|0015)
		echo "Model A+ 256MB";;
	a01040|a01041|a21041|a22042)
		echo "Pi 2 Model B 1GB";;
	900021)
		echo "Model A+ 512MB";;
	900032)
		echo "Model B+ 512MB";;
	900092|900093|920093)
		echo "Zero 512MB";;
	9000c1)
		echo "Zero W 512MB";;
	a02082|a22082|a32082)
		echo "Pi 3 Model B 1GB";;
	*)
		echo "Unknown revision $revision, please see https://elinux.org/RPi_HardwareHistory"
		exit 1;;
esac
	
	

